name: React App Deployment

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v16  # Updated to use Node.js version 16 (latest LTS)
      with:
        node-version: 16

    - name: Install Dependencies
      run: yarn

    - name: Build React App
      run: yarn build  # Adjust the command based on your project setup

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      uses: sethvilla/github-pages-deploy-action@4.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build

